# -*- coding: utf-8 -*-
"""cmpeworksheet1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yTI7gV4KQ3hDehD0iUQH_jl0nS3jBUXY
"""

"""
Stage : Development -01
@author : Ege Ergen , 120202011
@author : Giragos Başak , 119202045
"""
#we will import from BeatifulSoup to scrape the web
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
#IMDb top 250 list link provided
url = 'http://www.imdb.com/chart/top'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
movies = soup.select('td.titleColumn')
crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
ratings = [b.attrs.get('data-value')
        for b in soup.select('td.posterColumn span[name=ir]')]
 
list = []
#we store data in empty list 
for index in range(0, len(movies)):

    movie_string = movies[index].get_text()
    movie = (' '.join(movie_string.split()).replace('.', ''))
    movie_title = movie[len(str(index))+1:-7]
    year = re.search('\((.*?)\)', movie_string).group(1)
    place = movie[:len(str(index))-(len(movie))]
    data = {"place": place,
            "movie_title": movie_title,
            "rating": ratings[index],
            "year": year,
            "star_cast": crew[index],
            }
    list.append(data)
#finally we print the list that we have retrieved from the website
for movie in list:
    print(movie['place'], '-', movie['movie_title'], '('+movie['year'] +
        ') -', 'Starring:', movie['star_cast'], movie['rating'])